# Generated by Django 3.0.3 on 2022-04-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_materials_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materials',
        ),
    ]
