# Generated by Django 3.0.3 on 2022-04-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220409_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='tasks',
            field=models.ManyToManyField(to='api.Task'),
        ),
    ]
