# Generated by Django 3.0.3 on 2022-04-09 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_projects_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('sources', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Materials',
            new_name='Material',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.AddField(
            model_name='project',
            name='materials',
            field=models.ManyToManyField(to='api.Material'),
        ),
        migrations.AddField(
            model_name='task',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
    ]
