# Generated by Django 3.0.3 on 2022-04-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_material_related_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='materials',
            new_name='related_materials',
        ),
        migrations.AddField(
            model_name='project',
            name='related_tasks',
            field=models.ManyToManyField(to='api.Task'),
        ),
    ]
