# Generated by Django 3.0.3 on 2022-04-09 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220409_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='related_materials',
        ),
        migrations.AddField(
            model_name='project',
            name='related_materials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Material'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='related_tasks',
        ),
        migrations.AddField(
            model_name='project',
            name='related_tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Task'),
        ),
    ]
