# Generated by Django 3.0.3 on 2022-04-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220410_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='related_materials',
        ),
        migrations.RemoveField(
            model_name='project',
            name='related_tasks',
        ),
        migrations.AddField(
            model_name='project',
            name='materials',
            field=models.ManyToManyField(blank=True, to='api.Material'),
        ),
    ]
